# Generated by Django 4.2.3 on 2023-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to="books/%Y/%m/%d", verbose_name="Картинка"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, verbose_name="Название книги"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                ("year", models.IntegerField(verbose_name="Год издания")),
                ("pages", models.IntegerField(verbose_name="Страниц")),
                ("quantity", models.IntegerField(verbose_name="Количество книг")),
                ("avtive", models.BooleanField(default=False, verbose_name="Активный")),
                ("rating", models.FloatField(verbose_name="Рейтинг")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего редактирования"
                    ),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        related_name="Author", to="authors.author", verbose_name="Автор"
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
