# Generated by Django 4.2.3 on 2023-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Автор", "verbose_name_plural": "Авторы"},
        ),
        migrations.RemoveField(
            model_name="author",
            name="number",
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Автор"),
        ),
    ]
